Error: Undefined variable $code was used in outputOrLogError()
This problem was present since the framework born but never noticed
it, now it is fixed.

The $code variable is used to find the error code and render the
correct Error page to browser like 404 Not Found and 500 Internal
Server Error.